#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────


TOTAL_STAGES=8

# The credentials live outside the repo on purpose: okf-tools has no .gitignore,
# and jj snapshots the working copy automatically, so a key (or a .env naming
# one) dropped in the repo would be committed without anyone deciding to.
CONF_DIR="${CONF_DIR:-$HOME/.config/okfpub}"
ENV_FILE="$CONF_DIR/gdocs.env"
KEY_FILE="$CONF_DIR/gdocs-sa.json"
mkdir -p "$CONF_DIR"
chmod 700 "$CONF_DIR"

HAVE_GCLOUD=0
PREV_ACCOUNT=""
GCP_ORG=""

# die "msg" — a failed prerequisite must STOP the wizard. Continuing produced the
# worst outcome in practice: no project, so no service account, so stage 6's Drive
# share fails with "Sharing to email addresses without a Google account is not yet
# supported" — an error that points nowhere near the real cause.
die() {
  printf '\n  %s✗ %s%s\n\n' "$RED" "$1" "$RESET"
  shift || true
  for line in "$@"; do note "  $line"; done
  printf '\n'
  exit 1
}

banner "okfpub — Google Docs development destination"

# ── 1 ──────────────────────────────────────────────────────────────────────
stage "Prerequisites"
say "This provisions the DEVELOPMENT destination for the Google Docs backend:"
say "a GCP project, a service account, and a shared drive it can write into."
note "Nothing here is touched by CI. Tear it down when the backend ships (#154)."
printf '\n'
say "Credentials will be written to:"
note "  $ENV_FILE"
note "  $KEY_FILE  (chmod 600)"
printf '\n'

say "Shared drives are a Workspace feature, so every step must run as the"
say "Workspace identity — not a personal Google account."
ask GDOCS_WORKSPACE_ACCOUNT "Workspace account [yann@hodique.info]:"
[[ -z "$GDOCS_WORKSPACE_ACCOUNT" ]] && GDOCS_WORKSPACE_ACCOUNT="yann@hodique.info"
write_env GDOCS_WORKSPACE_ACCOUNT "$GDOCS_WORKSPACE_ACCOUNT"
# Google honours ?authuser=<email>, so every URL this wizard opens lands in the
# right account even when the browser's default session is a different one.
AUTH="authuser=$GDOCS_WORKSPACE_ACCOUNT"
printf '\n'

if command -v gcloud >/dev/null 2>&1; then
  HAVE_GCLOUD=1
  PREV_ACCOUNT=$(gcloud config get-value account 2>/dev/null || true)
  [[ "$PREV_ACCOUNT" == "(unset)" ]] && PREV_ACCOUNT=""
  say "gcloud active account: ${PREV_ACCOUNT:-none}"
  if [[ "$PREV_ACCOUNT" != "$GDOCS_WORKSPACE_ACCOUNT" ]]; then
    warn "gcloud is NOT authenticated as $GDOCS_WORKSPACE_ACCOUNT."
    note "The project and the drive can technically live under different accounts,"
    note "but keeping both under the Workspace identity avoids a lot of confusion."
    if gcloud auth list --format='value(account)' 2>/dev/null | grep -qx "$GDOCS_WORKSPACE_ACCOUNT"; then
      if confirm "Switch gcloud to $GDOCS_WORKSPACE_ACCOUNT for this setup?"; then
        gcloud config set account "$GDOCS_WORKSPACE_ACCOUNT" >/dev/null 2>&1 \
          && say "switched (your previous account is restored at the end)"
      fi
    else
      step "In another terminal: gcloud auth login $GDOCS_WORKSPACE_ACCOUNT"
      pause "Press Enter once that's done (or to carry on with the current account)."
      gcloud config set account "$GDOCS_WORKSPACE_ACCOUNT" >/dev/null 2>&1 || true
    fi
  fi
else
  warn "gcloud not found — the wizard will walk the console instead."
  note "Install it with: nix shell nixpkgs#google-cloud-sdk"
  SKIPPED+=("install gcloud for the automated path and the write verification")
fi
pause "Ready?"

# ── 2 ──────────────────────────────────────────────────────────────────────
stage "Accept the Cloud Terms of Service"
say "A Google account that has never opened the Cloud console cannot create"
say "projects: the API refuses with 'Callers must accept Terms of Service'."
say "There is no CLI for this — it has to be a browser visit, once per account."
printf '\n'
if (( HAVE_GCLOUD )) && gcloud projects list --limit=1 >/dev/null 2>&1; then
  say "$GDOCS_WORKSPACE_ACCOUNT can already list projects — ToS accepted."
else
  open_url "https://console.cloud.google.com/?$AUTH"
  step "Check the avatar top-right really is $GDOCS_WORKSPACE_ACCOUNT."
  step "Accept the Terms of Service if prompted (country + tick the box)."
  step "Wait until the console dashboard loads."
  pause "Press Enter once the dashboard is up."
fi

if (( HAVE_GCLOUD )); then
  GCP_ORG=$(gcloud organizations list --format='value(ID)' 2>/dev/null | head -n1 || true)
  if [[ -n "$GCP_ORG" ]]; then
    say "Organization: $GCP_ORG"
  else
    warn "No organization visible — the project will be created without a parent."
  fi
fi

# ── 3 ──────────────────────────────────────────────────────────────────────
stage "Google Cloud project"
DEFAULT_PROJECT="okfpub-gdocs-dev-$RANDOM"
say "A project to own the Docs/Drive API enablement and the service account."
ask GCP_PROJECT "Project id [$DEFAULT_PROJECT]:"
[[ -z "$GCP_PROJECT" ]] && GCP_PROJECT="$DEFAULT_PROJECT"

if (( HAVE_GCLOUD )); then
  if gcloud projects describe "$GCP_PROJECT" >/dev/null 2>&1; then
    say "Project $GCP_PROJECT already exists — reusing it."
  elif confirm "Create project $GCP_PROJECT now?"; then
    CREATE_ARGS=("$GCP_PROJECT")
    [[ -n "$GCP_ORG" ]] && CREATE_ARGS+=("--organization=$GCP_ORG")
    if ! CREATE_ERR=$(gcloud projects create "${CREATE_ARGS[@]}" 2>&1); then
      printf '%s\n' "$CREATE_ERR" | tail -8
      if printf '%s' "$CREATE_ERR" | grep -qi "Terms of Service"; then
        die "$GDOCS_WORKSPACE_ACCOUNT has not accepted the Cloud Terms of Service." \
            "Re-do stage 2 in the browser, then run this wizard again."
      fi
      die "Could not create project $GCP_PROJECT." \
          "Nothing downstream will work without it — fix this, then re-run."
    fi
  else
    die "A project is required." "Re-run when you are ready to create one."
  fi
else
  open_url "https://console.cloud.google.com/projectcreate?$AUTH"
  step "Create a project named $GCP_PROJECT and wait for it to finish."
  pause "Press Enter once the project exists."
fi
write_env GCP_PROJECT "$GCP_PROJECT"

# ── 4 ──────────────────────────────────────────────────────────────────────
stage "Enable the Docs and Drive APIs"
say "The backend calls documents.batchUpdate and the Drive v3 files endpoints."
if (( HAVE_GCLOUD )); then
  if confirm "Enable docs.googleapis.com and drive.googleapis.com on $GCP_PROJECT?"; then
    gcloud services enable docs.googleapis.com drive.googleapis.com \
      --project "$GCP_PROJECT" || warn "enable failed — do it in the console"
  else
    SKIPPED+=("enable docs.googleapis.com and drive.googleapis.com")
  fi
else
  open_url "https://console.cloud.google.com/apis/library/docs.googleapis.com?project=$GCP_PROJECT&$AUTH"
  step "Click Enable on the Google Docs API."
  pause "Press Enter when it's enabled."
  open_url "https://console.cloud.google.com/apis/library/drive.googleapis.com?project=$GCP_PROJECT&$AUTH"
  step "Click Enable on the Google Drive API."
  pause "Press Enter when it's enabled."
fi

# ── 5 ──────────────────────────────────────────────────────────────────────
stage "Service account and keyless access"
say "The publish identity. It owns no files — it only writes into a shared drive."
note "No JSON key is created. Google orgs enforce"
note "constraints/iam.managed.disableServiceAccountKeyCreation by default, and"
note "short-lived impersonated credentials are the better answer anyway."
SA_NAME="okfpub-gdocs"
GDOCS_SA_EMAIL="${SA_NAME}@${GCP_PROJECT}.iam.gserviceaccount.com"

if (( HAVE_GCLOUD )); then
  if gcloud iam service-accounts describe "$GDOCS_SA_EMAIL" --project "$GCP_PROJECT" >/dev/null 2>&1; then
    say "Service account already exists — reusing it."
  else
    gcloud iam service-accounts create "$SA_NAME" \
      --project "$GCP_PROJECT" \
      --display-name "okfpub Google Docs publisher" \
      || die "Could not create the service account." \
             "Stage 7 would then fail with 'Sharing to email addresses without a" \
             "Google account is not yet supported' — because it would not exist."
  fi

  # Impersonation needs the IAM Credentials API and token-creator on the SA itself.
  gcloud services enable iamcredentials.googleapis.com --project "$GCP_PROJECT" >/dev/null 2>&1 \
    || warn "could not enable iamcredentials.googleapis.com"
  gcloud iam service-accounts add-iam-policy-binding "$GDOCS_SA_EMAIL" \
    --project "$GCP_PROJECT" \
    --member="user:${GDOCS_WORKSPACE_ACCOUNT}" \
    --role="roles/iam.serviceAccountTokenCreator" >/dev/null 2>&1 \
    && say "granted roles/iam.serviceAccountTokenCreator to $GDOCS_WORKSPACE_ACCOUNT" \
    || warn "could not grant token-creator — stage 8 will fail without it"
  note "IAM propagation takes up to a minute; stage 8 retries."
else
  open_url "https://console.cloud.google.com/iam-admin/serviceaccounts/create?project=${GCP_PROJECT}&${AUTH}"
  step "Create a service account named '$SA_NAME'. Do NOT create a key."
  step "Open it → Permissions → Grant access → add ${GDOCS_WORKSPACE_ACCOUNT}"
  step "  with the role 'Service Account Token Creator'."
  pause "Press Enter once that's done."
fi

write_env GDOCS_SA_EMAIL "$GDOCS_SA_EMAIL"
write_env GDOCS_IMPERSONATE_SA "$GDOCS_SA_EMAIL"

# ── 6 ──────────────────────────────────────────────────────────────────────
stage "Create the shared drive"
say "It MUST be a shared drive, not a My Drive folder: a service account has no"
say "storage quota and cannot own files. A My Drive folder shared with it fails"
say "at write time with a misleading 403 storageQuotaExceeded."
note "Signed in as $GDOCS_WORKSPACE_ACCOUNT — check the avatar top-right before"
note "creating anything; a drive made by the wrong account is invisible to the rest."
printf '\n'
open_url "https://drive.google.com/drive/shared-drives?$AUTH"
step "Click 'New' (top left) and name the drive, e.g. 'okfpub dev'."
step "Open the new drive. Its URL ends with the drive id:"
note "  https://drive.google.com/drive/folders/<THIS IS THE ID>"
ask GDRIVE_FOLDER_ID "Paste the shared drive id:"
while [[ -z "$GDRIVE_FOLDER_ID" ]]; do
  warn "The drive id is required."
  ask GDRIVE_FOLDER_ID "Paste the shared drive id:"
done
write_env GDRIVE_FOLDER_ID "$GDRIVE_FOLDER_ID"

# ── 7 ──────────────────────────────────────────────────────────────────────
stage "Give the service account write access"
say "Permissions are inherited from the drive, so this is the only grant needed —"
say "every Doc created inside it is visible to whoever can see the drive."
printf '\n'
say "Add this member:"
printf '\n    %s%s%s\n\n' "$BOLD" "$GDOCS_SA_EMAIL" "$RESET"
open_url "https://drive.google.com/drive/folders/$GDRIVE_FOLDER_ID?$AUTH"
step "Drive name (top) → Manage members."
step "Paste the address above, set the role to 'Content manager', click Send."
warn "'Contributor' is NOT enough: it can create and trash files but not delete"
warn "them (canDelete=false), so cleanup fails in confusing ways."
note "Sharing with a service account sends no email — that's expected."
pause "Press Enter once it's added."

# ── 8 ──────────────────────────────────────────────────────────────────────
stage "Verify with a real write"
say "The failure this catches: an identity that looks provisioned but cannot"
say "actually create a file. It creates a throwaway Doc and trashes it again."

if (( HAVE_GCLOUD )); then
  if confirm "Run the write check now?"; then
    # gcloud's --impersonate-service-account IGNORES --scopes, yielding a
    # cloud-platform token that Drive rejects. Mint the token through the IAM
    # Credentials API instead, with the Drive scope stated explicitly — which is
    # also what the Go client library does.
    SA_TOKEN=""
    for attempt in 1 2 3 4 5 6; do
      USER_TOKEN=$(gcloud auth print-access-token 2>/dev/null || true)
      SA_TOKEN=$(curl -sS -X POST \
        "https://iamcredentials.googleapis.com/v1/projects/-/serviceAccounts/${GDOCS_SA_EMAIL}:generateAccessToken" \
        -H "Authorization: Bearer ${USER_TOKEN}" -H "Content-Type: application/json" \
        -d '{"scope":["https://www.googleapis.com/auth/drive"],"lifetime":"600s"}' 2>/dev/null \
        | sed -n 's/.*"accessToken"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p')
      [[ -n "$SA_TOKEN" ]] && break
      note "waiting for the token-creator grant to propagate (attempt ${attempt}/6)…"
      sleep 15
    done

    if [[ -z "$SA_TOKEN" ]]; then
      warn "Could not mint an impersonated token for $GDOCS_SA_EMAIL."
      note "Check that $GDOCS_WORKSPACE_ACCOUNT holds roles/iam.serviceAccountTokenCreator"
      note "on the service account, and that iamcredentials.googleapis.com is enabled."
      SKIPPED+=("run the write check — impersonation failed")
    else
      say "minted a Drive-scoped impersonated token"
      CREATE_CODE=$(curl -sS -o /tmp/okfpub-check.json -w '%{http_code}' -X POST \
        "https://www.googleapis.com/drive/v3/files?supportsAllDrives=true&fields=id" \
        -H "Authorization: Bearer ${SA_TOKEN}" -H "Content-Type: application/json" \
        -d "{\"name\":\"okfpub provisioning check\",\"mimeType\":\"application/vnd.google-apps.document\",\"parents\":[\"${GDRIVE_FOLDER_ID}\"]}")
      DOC_ID=$(sed -n 's/.*"id"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' /tmp/okfpub-check.json)
      if [[ "$CREATE_CODE" == "200" && -n "$DOC_ID" ]]; then
        printf '  %s✓ wrote%s a test Doc (%s)\n' "$GREEN" "$RESET" "$DOC_ID"
        # Trash, not delete: a Contributor cannot permanently delete, and trashing
        # works for every role that could have created the file.
        TRASH_CODE=$(curl -sS -o /dev/null -w '%{http_code}' -X PATCH \
          "https://www.googleapis.com/drive/v3/files/${DOC_ID}?supportsAllDrives=true" \
          -H "Authorization: Bearer ${SA_TOKEN}" -H "Content-Type: application/json" \
          -d '{"trashed":true}')
        if [[ "$TRASH_CODE" == "200" ]]; then
          printf '  %s✓ cleaned it up%s\n' "$GREEN" "$RESET"
        else
          warn "created it but could not trash it (HTTP $TRASH_CODE) — remove '$DOC_ID' by hand"
        fi
        say "The destination is ready."
      else
        warn "The write FAILED (HTTP $CREATE_CODE):"
        head -c 600 /tmp/okfpub-check.json; printf '\n\n'
        note "403 storageQuotaExceeded → the target is not a shared drive."
        note "404 → the service account is not a member of the drive. Re-check stage 7."
        SKIPPED+=("re-run the write check — it failed")
      fi
    fi
  else
    SKIPPED+=("run the write check")
  fi
else
  warn "Skipping the write check (needs gcloud)."
  SKIPPED+=("verify the service account can create a file in the shared drive")
fi

# Stage 1 may have switched gcloud to the Workspace account, and stage 7 activates
# the service account; either way, leave the shell as we found it.
if (( HAVE_GCLOUD )) && [[ -n "$PREV_ACCOUNT" ]]; then
  CURRENT=$(gcloud config get-value account 2>/dev/null || true)
  if [[ "$CURRENT" != "$PREV_ACCOUNT" ]]; then
    gcloud config set account "$PREV_ACCOUNT" >/dev/null 2>&1 || true
  fi
fi

finish
note "Load these into a shell with:  set -a; . $ENV_FILE; set +a"
note "Auth is keyless: the publisher impersonates $GDOCS_SA_EMAIL."
note "Record the drive id and service-account address on issue #154."
note "Tear the drive and project down when the backend ships."
printf '\n'
